---
- name: Install cinder {{ cinder_role }} packages & co
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items: packages

- name: ensure cinder sqlite is deleted
  file:
    dest: /var/lib/cinder/cinder.sqlite
    state: absent
