---
- name: Install cinder & co
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - cinder-api
    - cinder-scheduler
    - cinder-volume
    - python-cinderclient
    - python-mysqldb
    - tgt

- name: ensure cinder sqlite is deleted
  file:
    dest: /var/lib/cinder/cinder.sqlite
    state: absent
