---
packages:
  - swift
  - swift-account
  - swift-container
  - swift-object
  - xfsprogs
  - rsync

services:
  - swift-account
  - swift-account-auditor
  - swift-account-reaper
  - swift-account-replicator
  - swift-container
  - swift-container-auditor
  - swift-container-replicator
  - swift-container-updater
  - swift-object
  - swift-object-auditor
  - swift-object-replicator
  - swift-object-updater

config_files:
  - account-server.conf
  - container-server.conf
  - object-server.conf
