---
- name: restart keystone
  service:
    name: "{{ item }}"
    state: stopped
    enabled: yes
  with_items:
    - keystone
    - apache2

- name: update configuration files from templates
  template:
    src: keystone.conf
    dest: /etc/keystone/keystone.conf
    owner: root
    group: root
    mode: 0644

- name: ensure database is synced
  command: /usr/bin/keystone-manage db_sync

- name: restart keystone
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - keystone
    - apache2

# keystone seems to take a while...
- name: wait for keystone to come back up
  wait_for:
    host: "{{ keystone_endpoint_host }}"
    port: 35357

- name: create service tenant
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}"
    tenant: service
    tenant_description: "Service Tenant"

- name: add keystone endpoint information
  keystone_service:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}"
    region: "{{ openstack_region }}"
    name: keystone
    type: identity
    description: "Identity Service"
    public_url: "{{ keystone_public_url }}"
    internal_url: "{{ keystone_internal_url }}"
    admin_url: "{{ keystone_admin_url }}"

- name: create admin tenant
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}"
    tenant: admin
    tenant_description: "Admin Tenant"

- name: create admin user
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}"
    tenant: admin
    user: admin
    password: "{{ admin_password }}"

- name: create admin role and associate it with admin user
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}"
    tenant: admin
    user: admin
    role: admin

- name: create Member role and associate it with admin user
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}"
    tenant: admin
    user: admin
    role: Member

- name: create user role and associate it with admin user
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}"
    tenant: admin
    user: admin
    role: user

- name: Copy admin rcfiles
  template:
    src: "{{ item }}"
    dest: /root/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - admin.openrc
    - token.openrc
