---
- name: Install Keystone related packages
  apt:
    pkg: "{{ item }}"
    force: yes
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - keystone
    - libapache2-mod-wsgi
    - memcached
    - python-memcache
    - apache2

- name: Keep apache off port 80 and 443
  template:
    src: apache_ports.conf
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: 0644

- name: ensure keystone sqlite is deleted
  file:
    dest: /var/lib/keystone/keystone.sqlite
    state: absent
